serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'beacon-app'
        metrics_path: '/api/health'
        static_configs:
          - targets: ['beacon-service.beacon.svc.cluster.local:80']
