apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beacon-ingress
  namespace: beacon
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: beacon.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: beacon-service
                port:
                  number: 80
